In [0]:
import numpy as np
import pandas as pd

# Series In Pandas

In [0]:
# Series in Pandas are similar to NumPy arrays, the only difference being that we can label elemnts in a series.
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [0]:
pd.Series(data=my_data) #Notice the pre-existing indices in the series

0    10
1    20
2    30
dtype: int64

In [0]:
pd.Series(data=my_data,index=labels) #custom indices

a    10
b    20
c    30
dtype: int64

In [0]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [0]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [0]:
# Accessing values from a Series

ser1 = pd.Series([1,2,10,4],['US','China','India','Japan'])
ser1['India']

10

In [0]:
ser2 = pd.Series([1,2,5,4],['US','China','Australia','Japan'])

In [0]:
ser1 + ser2

US            2
China         4
Australia    10
Japan         8
dtype: int64

# DataFrames in Pandas

In [0]:
from numpy.random import randn

In [0]:
np.random.seed(101)

In [0]:
df = pd.DataFrame(randn(5,4),['a','b','c','d','e'],['w','x','y','z']) # Declaring a DataFrame

In [0]:
df

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
# Extracting values from a DataFrame

df['w']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [0]:
df.w # SQL-Like statement to access values

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [0]:
df[['x','y']]

          x         y
a  0.628133  0.907969
b -0.319318 -0.848077
c  0.740122  0.528813
d -0.758872 -0.933237
e  1.978757  2.605967

In [0]:
df['new'] = df['w'] + df['y']

In [0]:
df

          w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [0]:
df.drop('new') # Here, by default axis=0, which means we are referring to indices(rows) of dataframe to be dropped.

ValueError: labels ['new'] not contained in axis

In [0]:
df.drop('new',axis = 1) # This works! However, it is not reflected in original dataframe,i.e. , it doesn't happen inplace.

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df

          w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [0]:
df.drop('new',axis = 1, inplace=True) # This solves our problem!

In [0]:
df

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
# Selecting Rows of a DataFrame

df.loc['a'] # This shows rows in a DataFrame are Series as well.

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [0]:
df.iloc[3] # Index based access of rows in a Dataframe.

w    0.188695
x   -0.758872
y   -0.933237
z    0.955057
Name: d, dtype: float64

In [0]:
# Accessing subsets of data from a DataFrame

df.loc['b','z']

0.6059653494949336

In [0]:
df.loc[['c','d'],['w','x']]

          w         x
c -2.018168  0.740122
d  0.188695 -0.758872

In [0]:
df > 0

       w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [0]:
df['x'] > 0

a     True
b    False
c     True
d    False
e     True
Name: x, dtype: bool

In [0]:
df[df['x'] > 0] # Conditional selction in DataFrames

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df[df['y'] > 0]['z']

a    0.503826
c   -0.589001
e    0.683509
Name: z, dtype: float64

In [0]:
df[df['y'] > 0][['z','w']]

          z         w
a  0.503826  2.706850
c -0.589001 -2.018168
e  0.683509  0.190794

In [0]:
boolseries = df['w'] > 0
result = df[boolseries]
mycols = ['y','x'] 
result[mycols]  # Alternate code to the previous code

          y         x
a  0.907969  0.628133
b -0.848077 -0.319318
d -0.933237 -0.758872
e  2.605967  1.978757

In [0]:
# Multiple Conditions 

df[(df['w'] > 0) and (df['y'] > 1)] # Error results because "And" is not compatible with a Series.

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [0]:
df[(df['w'] > 0) & (df['y'] > 1)]

          w         x         y         z
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df.reset_index() # used to reset the indices of the dataframe to integers. However, it is still not inPlace.

  index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [0]:
df

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [0]:
df.reset_index(inplace=True)

In [0]:
df

  index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [0]:
df

  index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [0]:
# Adding a new Column in a DataFrame

newind = 'CA NY SC ST GN'.split()

In [0]:
newind

['CA', 'NY', 'SC', 'ST', 'GN']

In [0]:
df['states'] = newind

In [0]:
df

  index         w         x         y         z states
0     a  2.706850  0.628133  0.907969  0.503826     CA
1     b  0.651118 -0.319318 -0.848077  0.605965     NY
2     c -2.018168  0.740122  0.528813 -0.589001     SC
3     d  0.188695 -0.758872 -0.933237  0.955057     ST
4     e  0.190794  1.978757  2.605967  0.683509     GN

In [0]:
df.set_index('states') #creating new index in the dataframe. However, this is still not inPlace.

       index         w         x         y         z
states
CA         a  2.706850  0.628133  0.907969  0.503826
NY         b  0.651118 -0.319318 -0.848077  0.605965
SC         c -2.018168  0.740122  0.528813 -0.589001
ST         d  0.188695 -0.758872 -0.933237  0.955057
GN         e  0.190794  1.978757  2.605967  0.683509

In [0]:
# Working With Missing Data

d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [0]:
df = pd.DataFrame(d)

In [0]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [0]:
df.dropna() # drops all rows(axis=0) or columns(axis=1) with either one / multiple null values.

     A    B  C
0  1.0  5.0  1

In [0]:
df.dropna(thresh=2) # drops all rows(axis=0) or columns(axis=1) with no. of values equal to thresh limit.

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [0]:
df.fillna(value="Fill Value") # Fills the values wherever null occurs.

            A           B  C
0           1           5  1
1           2  Fill Value  2
2  Fill Value  Fill Value  3

In [0]:
df['A'].fillna(value=df['A'].mean()) # We often replace the missing values with the mean of the column/row.

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# GroupBy in Pandas

In [0]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [0]:
df = pd.DataFrame(data)

In [0]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [0]:
byComp = df.groupby('Company')

In [0]:
byComp.mean() # We can similarily have sum(),std(),and many more functions.

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [0]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

# Operations in Pandas

In [2]:
import numpy as np
import pandas as pd


df = pd.DataFrame({'col1':[1,2,3,4],
                  'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [3]:
#Checking for unique values within a column

df['col3'].unique()

array(['abc', 'def', 'ghi', 'xyz'], dtype=object)

In [4]:
df['col3'].nunique() # Gives the number of unique values in a column

4

In [5]:
df['col2'].value_counts() # Gives the number of times each unique value occurs in a column

444    2
555    1
666    1
Name: col2, dtype: int64

In [0]:
def times2(x):
  return x*2

In [8]:
df['col1'].apply(times2) # apply() is used to broadcast the given function across each of the column elements

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [9]:
df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [10]:
df.drop('col2',axis=1) # Drops the specified column, Notice the axis is 1. (Although this operation is not inplace)

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [11]:
df.columns # This tells us that the indices of the columns are in fact attributes of the DataFrame.

Index(['col1', 'col2', 'col3'], dtype='object')

In [12]:
df.sort_values('col2') # Sorts the dataframe w.r.t. the values of the column specified.

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [14]:
df.isnull() # Returns a DataFrame of boolean values corresponding to the Existence/Non-existence of Null values.

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [0]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
       'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [16]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [18]:
df.pivot_table(values='D',index=['A','B'],columns='C')

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# Data Input and Output in Pandas

In [19]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading SQLAlchemy-1.2.5.tar.gz (5.6MB)
    100% |████████████████████████████████| 5.6MB 237kB/s
Building wheels for collected packages: sqlalchemy
  Running setup.py bdist_wheel for sqlalchemy ... - \ | / - \ | / - done
  Stored in directory: /content/.cache/pip/wheels/61/22/7c/7f7a00946677df88d7072eb5c225108fc5c1e7e68b56a72689
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.2.5

In [20]:
!pip install lxml

Collecting lxml
  Downloading lxml-4.2.1-cp36-cp36m-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.7MB 228kB/s
Installing collected packages: lxml
Successfully installed lxml-4.2.1

In [21]:
!pip install html5lib

Requirement already satisfied: html5lib in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from html5lib)

In [22]:
!pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python3.6/dist-packages

In [0]:
import pandas as pd

In [28]:
pd.read_csv('SacramentocrimeJanuary2006.csv') # used to read from a source (Here the source is a .csv file)

FileNotFoundError: ignored

In [29]:
df = pd.read_csv('xyz.csv') 

df.to_csv('My_Output',index=False)     # Used to write to a file

FileNotFoundError: ignored

In [32]:
pd.read_excel('abc.xlsx',sheetname="sheet1")  # reading from an excel sheet

/usr/local/lib/python3.6/dist-packages/pandas/util/_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

FileNotFoundError: ignored

In [31]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-1.1.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 3.3MB/s
Installing collected packages: xlrd
Successfully installed xlrd-1.1.0

In [33]:
df.to_excel('Example2.xlsx',sheet_name="new") # Writing to an excel sheet

ModuleNotFoundError: ignored

In [0]:
data = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html') # Reading from HTML file

In [36]:
data[0].head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Washington Federal Bank for Savings,Chicago,IL,30570,Royal Savings Bank,"December 15, 2017","February 21, 2018"
1,The Farmers and Merchants State Bank of Argonia,Argonia,KS,17719,Conway Bank,"October 13, 2017","February 21, 2018"
2,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb","May 26, 2017","July 26, 2017"
3,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,"May 5, 2017","March 22, 2018"
4,First NBC Bank,New Orleans,LA,58302,Whitney Bank,"April 28, 2017","December 5, 2017"